// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://uhlynnfhpvecjtbyrcib.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InVobHlubmZocHZlY2p0YnlyY2liIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDcxMzY4OTIsImV4cCI6MjA2MjcxMjg5Mn0.8AMbb64tSSTJ5v6BDd5U7V0XTAcMmcxLKZ2_6yoOI50";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);